### ISSUE TITLE
Trellis (Library) do not work on Arduino Zero Pro

### ISSUE THREAD

**Issue by SierraX369** [adafruit/Adafruit_Trellis_Library#8]
Good Morning!

Just test to connect Trellis with Arduino Zero Pro. When I try to compile on Arduino IDE 1.7.3 on a MBP got the compiling errors:

/Users/SierraX369/Documents/Arduino/libraries/Adafruit_Trellis_Library/Adafruit_Trellis.cpp: In member function 'bool Adafruit_Trellis::isKeyPressed(uint8_t)':
/Users/dmader/Documents/Arduino/libraries/Adafruit_Trellis_Library/Adafruit_Trellis.cpp:70:36: error: '_BV' was not declared in this scope
   return (keys[k>>4] & _BV(k & 0x0F));
                                    ^
/Users/SierraX369/Documents/Arduino/libraries/Adafruit_Trellis_Library/Adafruit_Trellis.cpp: In member function 'bool Adafruit_Trellis::wasKeyPressed(uint8_t)':
/Users/dmader/Documents/Arduino/libraries/Adafruit_Trellis_Library/Adafruit_Trellis.cpp:75:40: error: '_BV' was not declared in this scope
   return (lastkeys[k>>4] & _BV(k & 0x0F));
                                        ^
/Users/SierraX369/Documents/Arduino/libraries/Adafruit_Trellis_Library/Adafruit_Trellis.cpp: In member function 'boolean Adafruit_Trellis::isLED(uint8_t)':
/Users/dmader/Documents/Arduino/libraries/Adafruit_Trellis_Library/Adafruit_Trellis.cpp:93:48: error: '_BV' was not declared in this scope
   return ((displaybuffer[x >> 4] & _BV(x & 0x0F)) > 0);
                                                ^
/Users/SierraX369/Documents/Arduino/libraries/Adafruit_Trellis_Library/Adafruit_Trellis.cpp: In member function 'void Adafruit_Trellis::setLED(uint8_t)':
/Users/dmader/Documents/Arduino/libraries/Adafruit_Trellis_Library/Adafruit_Trellis.cpp:98:40: error: '_BV' was not declared in this scope
   displaybuffer[x >> 4] |= _BV(x & 0x0F);
                                        ^
/Users/SierraX369/Documents/Arduino/libraries/Adafruit_Trellis_Library/Adafruit_Trellis.cpp: In member function 'void Adafruit_Trellis::clrLED(uint8_t)':
/Users/dmader/Documents/Arduino/libraries/Adafruit_Trellis_Library/Adafruit_Trellis.cpp:103:41: error: '_BV' was not declared in this scope
   displaybuffer[x >> 4] &= ~_BV(x & 0x0F);
                                         ^

For Arduino Leonardo my sketch is compiling well.

Kind Regards
SierraX369

**Comment by ladyada** [comment]
yah Zero doesnt have _BV 
you migtht be able to 
`#define _BV(bit) (1 << (bit)) `
at the top of the file
